import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Users } from "../util/user";
import { useState, useEffect } from "react";
import Table from "../components/Table";

export default function Home({ d }) {
  const [query, setQuery] = useState("");
  const keys = ["first_name", "last_name", "email"];
  const [data, setData] = useState(d);

  useEffect(() => {
    const fetchUser = async () => {
      const res = await fetch(`http://localhost:3000/api/?q=${query}`);
      const data = await res.json();
      setData(data);
    };
    if (query.length > 2) fetchUser();
  }, [query]);

  const search = (data) => {
    return data.filter(
      (item) =>
        // item.first_name.toLowerCase().includes(query) ||
        // item.last_name.toLowerCase().includes(query) ||
        // item.email.toLowerCase().includes(query)
        keys.some((key) => item[key].toLowerCase().includes(query)) // some method equivalent to || ...||
    );
  };

  return (
    <div className={styles.app}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input
        type="text"
        placeholder="Search..."
        className={styles.search}
        onChange={(e) => setQuery(e.target.value)}
      />
      {/* <ul className="list">
          {Users.filter((user) =>
            user.first_name.toLowerCase().includes(query)
          ).map((user) => (
            <li key={user.id} className="listItem">
              {user.first_name}
            </li>
          ))}
        </ul> */}
      <Table data={data} />
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch("http://localhost:3000/api/");
  const data = await res.json();
  // console.log(data);
  return {
    props: { d: data },
  };
};
