import Head from "next/head";
import { GetServerSideProps } from "next";
import Image from "next/image";
import Featured from "../components/Featured";
import PizzaList from "../components/PizzaList";
import styles from "../styles/Home.module.scss";
import axios from "axios";
import PIZZA from "../util/Pizza";

const Home: React.FC<{ pizzaList: PIZZA[] }> = (props) => {
  // console.log(props);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured />
      <PizzaList pizzaList={props.pizzaList} />
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await axios.get("http://localhost:3000/api/products");
  // console.log(res.data);
  return {
    props: {
      pizzaList: res.data,
    },
  };
};

export default Home;
